name: build

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # pin@v6
        with:
          persist-credentials: false

      - name: bootstrap
        run: script/bootstrap

      - name: build
        run: script/build
